const { test } = require('node:test');
const assert = require('node:assert/strict');
const { createCaptureHandler } = require('../services/capture.service');
const admin = require('../middleware/growth-admin');
function response(){return {code:200,status(n){this.code=n;return this;},json(v){this.body=v;return this;},set(){}};}
const valid={name:'Owner',email:'OWNER@example.com',message:'Please fix the contact page',website:'https://example.com'};
test('saves details and attribution before owner notification',async()=>{let saved,mail;const res=response();await createCaptureHandler({Request:{create:async d=>(saved=d,{_id:'1'}),updateOne:async()=>{}},notify:async d=>mail=d})({body:{...valid,attribution:{utm_source:'youtube',utm_content:'x@y.com'}}},res);assert.equal(res.code,201);assert.equal(saved.message,valid.message);assert.equal(saved.email,'owner@example.com');assert.equal(saved.attribution.utm_source,'youtube');assert.equal(saved.attribution.utm_content,undefined);assert.equal(mail.message,valid.message);});
test('SMTP failure still confirms durable capture',async()=>{const res=response();await createCaptureHandler({Request:{create:async()=>({_id:'1'})},notify:async()=>{throw Error();}})({body:valid},res);assert.equal(res.code,201);assert.equal(res.body.notification,'pending');});
test('database failure never sends or reports success',async()=>{let sent=false;const res=response();await createCaptureHandler({Request:{create:async()=>{throw Error();}},notify:async()=>sent=true})({body:valid},res);assert.equal(res.code,503);assert.equal(sent,false);});
test('invalid input cannot reach database',async()=>{for(const body of [{...valid,email:{}},{...valid,name:''},{...valid,website:'javascript:alert(1)'},{...valid,message:'a'.repeat(5001)}]){let wrote=false;const res=response();await createCaptureHandler({Request:{create:async()=>wrote=true},notify:async()=>{}})({body},res);assert.equal(res.code,400);assert.equal(wrote,false);}});
test('owner guard fails closed and rejects other signed-in users',()=>{process.env.GROWTH_ADMIN_USER_ID='owner';for(const req of [{},{isAuthenticated:()=>true,user:{_id:'other'}}]){let next=false;const res=response();admin(req,res,()=>next=true);assert.equal(res.code,403);assert.equal(next,false);}let allowed=false;admin({isAuthenticated:()=>true,user:{_id:'owner'}},response(),()=>allowed=true);assert.equal(allowed,true);delete process.env.GROWTH_ADMIN_USER_ID;});
